### ISSUE TITLE
[Question] Run with Ultralite mk4?

### ISSUE THREAD

**Issue by maxkolenko** [Hecsall/motu-simple-control-panel-tauri#1]
Can this project control Motu Ultralite mk4?

**Comment by Hecsall** [comment]
Hi @maxkolenko, as long as the MK4 exposes a `/datastore` endpoint on the web interface yes, it should work.

From a quick Google search it appears the MK4 has the same API as the UltraLite AVB that I own, but keep in mind that the interface of my app is supposed to work with the channel layout of my interface. 
Still, if you can edit some HTML code inside `/pages/index.jsx` you can easily customize it for it to work with your own setup.

Let me know if you have any doubts!

**Comment by maxkolenko** [comment]
Hi, thank you for the detailed answer!
